language: rust
rust:
    - nightly

script:
    - cargo build --verbose --all
    - cargo doc --verbose
    - cargo test --verbose
    - cargo build --examples --verbose --all

branches:
    only:
        - master
